PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS ATLETA;
CREATE TABLE ATLETA(
    ID_ATLETA INT,
    NOME VARCHAR(80) NOT NULL,
    GENERO CHAR(1),
    DATA_DE_NASCIMENTO DATE NOT NULL,
    CONSTRAINT ATLETA_PK PRIMARY KEY (ID_ATLETA),
    CONSTRAINT GENERO_INVALIDO CHECK(GENERO='M' OR GENERO='F')
);


DROP TABLE IF EXISTS CLUBE;
CREATE TABLE CLUBE(
    ID_CLUBE INT,
    NOME VARCHAR(50) NOT NULL,
    DATA_DE_FUNDACAO DATE NOT NULL,
    CORES VARCHAR(20),
    CONSTRAINT CLUBE_PK PRIMARY KEY (ID_CLUBE)
);


DROP TABLE IF EXISTS CONTRATO;
CREATE TABLE CONTRATO(
    ID_CONTRATO INT,
    ID_ATLETA INT NOT NULL,
    ID_CLUBE INT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    CONSTRAINT CAC_PK PRIMARY KEY (ID_CONTRATO),
    CONSTRAINT CAC_UNIQUE UNIQUE (ID_ATLETA, ID_CLUBE, DATA_INICIO),
    CONSTRAINT CAC_FK1 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA,
    CONSTRAINT CAC_FK2 FOREIGN KEY (ID_CLUBE) REFERENCES CLUBE,
    CONSTRAINT DATAS_VALIDAS CHECK (DATA_INICIO <= DATA_FIM)
);


DROP TABLE IF EXISTS EVENTO;
CREATE TABLE EVENTO(
    ID_EVENTO INT PRIMARY KEY,
    GENERO CHAR(1),
    TIPO VARCHAR(30) NOT NULL,
    CONSTRAINT TIPO_EVENTO_VALIDO CHECK(TIPO = '60M' OR TIPO = '60MB' OR TIPO = '100M' OR TIPO = '100MB' OR TIPO = '110MB' OR TIPO = '200M' OR TIPO = '300M' OR TIPO = '300MB' OR TIPO = '400M' OR TIPO = '400MB' OR TIPO = '800M' OR TIPO = '1000M' OR TIPO = '1500M' OR TIPO = '3000M' OR TIPO = '3000MO' OR TIPO = '5000M' OR TIPO = '10000M' OR TIPO = '50KmM' OR TIPO = '20KmM' OR TIPO = 'MARATONA' OR TIPO = 'COMPRIMENTO' OR TIPO = 'ALTURA' OR TIPO = 'VARA' OR TIPO = 'TRIPLO' OR TIPO = 'PESO' OR TIPO = 'DISCO' OR TIPO = 'DARDO' OR TIPO = 'MARTELO' OR TIPO = 'DECATLO' OR TIPO = 'HEPTATLO' OR TIPO = 'PENTATLO' OR TIPO = 'TRIATLO' OR TIPO = '4x100M' OR TIPO = '4x400M' OR TIPO = 'ESTAFETA')
    CONSTRAINT GENERO_INVALIDO CHECK(GENERO='M' OR GENERO='F')
);


DROP TABLE IF EXISTS MARCA;
CREATE TABLE MARCA(
    ID_EVENTO INT NOT NULL,
    ID_ATLETA INT NOT NULL,
    MARCA FLOAT NOT NULL,
    DATA1 DATE NOT NULL,
    CONSTRAINT M_UNIQUE UNIQUE (ID_EVENTO, ID_ATLETA, MARCA, DATA1),
    CONSTRAINT CEA_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEA_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA
);


DROP TABLE IF EXISTS ESCALAO;
CREATE TABLE ESCALAO(
    ID_ESCALAO INT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    GENERO CHAR(1),
    IDADE_MINIMA INT,
    IDADE_MAXIMA INT,
    CONSTRAINT GENERO_INVALIDO CHECK(GENERO = 'M' OR GENERO = 'F')
);


DROP TABLE IF EXISTS EVENTO_ESCALAO;
CREATE TABLE EVENTO_ESCALAO(
    ID_EVENTO INT,
    ID_ESCALAO INT,
    CONSTRAINT CEE_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEE_FK2 FOREIGN KEY (ID_ESCALAO) REFERENCES ESCALAO
); /*confirmar se precisa primary key*/


DROP TABLE IF EXISTS LOCAL1;
CREATE TABLE LOCAL1(
    ID_LOCAL INT PRIMARY KEY,
    PAIS VARCHAR(20),
    CIDADE VARCHAR(30) NOT NULL
);


DROP TABLE IF EXISTS EVENTO_LOCAL;
CREATE TABLE EVENTO_LOCAL(
    ID_EVENTO INT,
    ID_LOCAL INT,
    CONSTRAINT CEL_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEL_FK2 FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL1
);/*confirmar se precisa primary key*/


DROP TABLE IF EXISTS TIPO_EVENTO;
CREATE TABLE TIPO_EVENTO(
    ID_TIPO_EVENTO INT PRIMARY KEY,
    NOME CHAR(2),
    CONSTRAINT NOME_INVALIDO CHECK(NOME = 'pc' OR NOME = 'al')
);


DROP TABLE IF EXISTS EVENTO_TIPO_EVENTO;
CREATE TABLE EVENTO_TIPO_EVENTO(
    ID_EVENTO INT,
    ID_TIPO_EVENTO INT,
    CONSTRAINT CEE_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEE_FK2 FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPO_EVENTO
);


DROP TABLE IF EXISTS HEPTATLO;
CREATE TABLE HEPTATLO(
    ID_HEPTATLO INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CHE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO
);


DROP TABLE IF EXISTS DECATLO;
CREATE TABLE DECATLO(
    ID_DECATLO INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CDE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO
);


DROP TABLE IF EXISTS SALTO;
CREATE TABLE SALTO(
    ID_SALTO INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    CONSTRAINT CSE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CSD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CSH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO
);


DROP TABLE IF EXISTS LANCAMENTO;
CREATE TABLE LANCAMENTO(
    ID_LANCAMENTO INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    PESO FLOAT,
    CONSTRAINT CLE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CLD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CLH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO,
    CONSTRAINT PESO_INVALIDO CHECK(PESO = 3 OR PESO = 4 OR PESO = 5 OR PESO = 6 OR PESO = 7 OR PESO = 500 OR PESO = 600 OR PESO = 700 OR PESO = 800 OR PESO = 1 OR PESO = 1.5 OR PESO = 1.75 OR PESO = 2)
);


DROP TABLE IF EXISTS CORRIDA;
CREATE TABLE CORRIDA(
    ID_CORRIDA INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    CONSTRAINT CCE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CCD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CCH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO 
);


DROP TABLE IF EXISTS ESTAFETA;
CREATE TABLE ESTAFETA(
    ID_ESTAFETA INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CEE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO 
);


DROP TABLE IF EXISTS CORRIDA_ESTAFETA;
CREATE TABLE CORRIDA_ESTAFETA(
    ID_CORRIDA INT,
    ID_EVENTO INT,
    CONSTRAINT CCE_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,   
    CONSTRAINT CCE_FK2 FOREIGN KEY (ID_CORRIDA) REFERENCES CORRIDA
);


DROP TABLE IF EXISTS PERCURSO;
CREATE TABLE PERCURSO(
    ID_ESTAFETA INT,
    ID_ATLETA INT,
    PERCURSO INT,
    CONSTRAINT CEA_FK1 FOREIGN KEY (ID_ESTAFETA) REFERENCES ESTAFETA,
    CONSTRAINT CEA_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA,
    CONSTRAINT PERCURSO_INVALIDO CHECK(PERCURSO = 1 OR PERCURSO = 2 OR PERCURSO = 3 OR PERCURSO = 4),
    CONSTRAINT CEA_UNIQUE UNIQUE (ID_ESTAFETA, ID_ATLETA, PERCURSO)
);