PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS MARCA_DISTANCIA;
DROP TABLE IF EXISTS MARCA_TEMPO;
DROP TABLE IF EXISTS MARCA_PONTOS;
DROP TABLE IF EXISTS ESCALAO2;
DROP TABLE IF EXISTS EVENTO_ESCALAO;
DROP TABLE IF EXISTS HEPTATLO;
DROP TABLE IF EXISTS SALTO;
DROP TABLE IF EXISTS LANCAMENTO;
DROP TABLE IF EXISTS CORRIDA_ESTAFETA;
DROP TABLE IF EXISTS CORRIDA;
DROP TABLE IF EXISTS PERCURSO;
DROP TABLE IF EXISTS ESTAFETA;
DROP TABLE IF EXISTS ATLETA;
DROP TABLE IF EXISTS CLUBE;
DROP TABLE IF EXISTS ESCALAO1;
DROP TABLE IF EXISTS EVENTO_LOCAL;
DROP TABLE IF EXISTS EVENTO_TIPO_EVENTO;
DROP TABLE IF EXISTS TIPO_EVENTO;
DROP TABLE IF EXISTS DECATLO;
DROP TABLE IF EXISTS LOCAL1;
DROP TABLE IF EXISTS EVENTO;



CREATE TABLE ATLETA(
    ID_ATLETA INT,
    NOME VARCHAR(80) NOT NULL,
    GENERO CHAR(1) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    CONSTRAINT ATLETA_PK PRIMARY KEY (ID_ATLETA),
    CONSTRAINT GENERO_VALIDO CHECK(GENERO='M' OR GENERO='F')
);


CREATE TABLE CLUBE(
    ID_CLUBE INT,
    NOME VARCHAR(50) NOT NULL,
    DATA_DE_FUNDACAO DATE NOT NULL,
    CORES VARCHAR(20),
    CONSTRAINT CLUBE_PK PRIMARY KEY (ID_CLUBE)
);



CREATE TABLE CONTRATO(
    ID_ATLETA INT NOT NULL,
    ID_CLUBE INT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    CONSTRAINT CAC_PK PRIMARY KEY (ID_ATLETA, DATA_INICIO),
    CONSTRAINT CAC_UNIQUE UNIQUE (ID_ATLETA, ID_CLUBE, DATA_INICIO),
    CONSTRAINT CAC_FK1 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA,
    CONSTRAINT CAC_FK2 FOREIGN KEY (ID_CLUBE) REFERENCES CLUBE,
    CONSTRAINT DATAS_VALIDAS CHECK (DATA_INICIO <= DATA_FIM)
);


CREATE TABLE EVENTO(
    ID_EVENTO INT,
    GENERO CHAR(1) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    CONSTRAINT TIPO_EVENTO_VALIDO CHECK(TIPO = '60M' OR TIPO = '60MB' OR TIPO = '100M' OR TIPO = '100MB' OR TIPO = '110MB' OR TIPO = '200M' OR TIPO = '300M' OR TIPO = '300MB' OR TIPO = '400M' OR TIPO = '400MB' OR TIPO = '800M' OR TIPO = '1000M' OR TIPO = '1500M' OR TIPO = '3000M' OR TIPO = '3000MO' OR TIPO = '5000M' OR TIPO = '10000M' OR TIPO = '50KmM' OR TIPO = '20KmM' OR TIPO = 'MARATONA' OR TIPO = 'COMPRIMENTO' OR TIPO = 'ALTURA' OR TIPO = 'VARA' OR TIPO = 'TRIPLO' OR TIPO = 'PESO' OR TIPO = 'DISCO' OR TIPO = 'DARDO' OR TIPO = 'MARTELO' OR TIPO = 'DECATLO' OR TIPO = 'HEPTATLO' OR TIPO = 'PENTATLO' OR TIPO = 'TRIATLO' OR TIPO = '4x100M' OR TIPO = '4x400M'),
    CONSTRAINT GENERO_VALIDO CHECK(GENERO='M' OR GENERO='F'),
    CONSTRAINT EVE_PK PRIMARY KEY (ID_EVENTO)
);



CREATE TABLE MARCA_DISTANCIA(
    ID_EVENTO INT NOT NULL,
    ID_ATLETA INT NOT NULL,
    MARCA FLOAT NOT NULL,
    DATA1 DATE NOT NULL,
    RN BOOLEAN DEFAULT 0,
    CONSTRAINT MD_PK PRIMARY KEY (ID_EVENTO,ID_ATLETA),
    CONSTRAINT MD_UNIQUE UNIQUE (ID_EVENTO, ID_ATLETA, MARCA, DATA1),
    CONSTRAINT RNED CHECK(RN = TRUE OR RN = FALSE),
    CONSTRAINT MD_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT MD_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA
);


CREATE TABLE MARCA_TEMPO(
    ID_EVENTO INT NOT NULL,
    ID_ATLETA INT NOT NULL,
    MARCA VARCHAR(15) NOT NULL,
    DATA1 DATE NOT NULL,
    RN BOOLEAN DEFAULT 0,
    CONSTRAINT MT_PK PRIMARY KEY (ID_EVENTO,ID_ATLETA),
    CONSTRAINT MT_UNIQUE UNIQUE (ID_EVENTO, ID_ATLETA, MARCA, DATA1),
    CONSTRAINT RNET CHECK(RN = TRUE OR RN = FALSE),
    CONSTRAINT MT_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT MT_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA
);


CREATE TABLE MARCA_PONTOS(
    ID_EVENTO INT NOT NULL,
    ID_ATLETA INT NOT NULL,
    MARCA INT NOT NULL,
    DATA1 DATE NOT NULL,
    RN BOOLEAN DEFAULT 0,
    CONSTRAINT MP_PK PRIMARY KEY (ID_EVENTO,ID_ATLETA),
    CONSTRAINT MP_UNIQUE UNIQUE (ID_EVENTO, ID_ATLETA, MARCA, DATA1),
    CONSTRAINT RNEP CHECK(RN = TRUE OR RN = FALSE),
    CONSTRAINT MP_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT MP_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA
);


CREATE TABLE ESCALAO1(
    ID_ESCALAO INT,
    NOME VARCHAR(20) NOT NULL,
    GENERO CHAR(1),
    CONSTRAINT CE1_PK PRIMARY KEY (ID_ESCALAO),
    CONSTRAINT GENERO_VALIDO CHECK(GENERO = 'M' OR GENERO = 'F')
);


CREATE TABLE ESCALAO2(
    NOME VARCHAR(20) NOT NULL,
    GENERO CHAR(1),
    IDADE_MINIMA INT,
    IDADE_MAXIMA INT,
    CONSTRAINT CE2_PK PRIMARY KEY (NOME, GENERO),
    CONSTRAINT GENERO_VALIDO CHECK(GENERO = 'M' OR GENERO = 'F'),
    CONSTRAINT IDADE_VALIDA CHECK(IDADE_MINIMA < IDADE_MAXIMA)
);


CREATE TABLE EVENTO_ESCALAO(
    ID_EVENTO INT,
    ID_ESCALAO INT,
    CONSTRAINT CEE_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEE_FK2 FOREIGN KEY (ID_ESCALAO) REFERENCES ESCALAO1,
    CONSTRAINT CEE_PK PRIMARY KEY (ID_EVENTO, ID_ESCALAO)
); 


CREATE TABLE LOCAL1(
    ID_LOCAL INT PRIMARY KEY,
    PAIS VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL
);



CREATE TABLE EVENTO_LOCAL(
    ID_EVENTO INT,
    ID_LOCAL INT,
    CONSTRAINT CEL_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEL_FK2 FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL1,
    CONSTRAINT CEL_PK PRIMARY KEY (ID_EVENTO, ID_LOCAL)
);



CREATE TABLE TIPO_EVENTO(
    ID_TIPO_EVENTO INT PRIMARY KEY,
    NOME CHAR(2),
    CONSTRAINT NOME_VALIDO CHECK(NOME = 'pc' OR NOME = 'al')
);



CREATE TABLE EVENTO_TIPO_EVENTO(
    ID_EVENTO INT,
    ID_TIPO_EVENTO INT,
    CONSTRAINT CEE_FK1 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CEE_FK2 FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPO_EVENTO
);



CREATE TABLE HEPTATLO(
    ID_HEPTATLO INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CHE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO
);



CREATE TABLE DECATLO(
    ID_DECATLO INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CDE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO
);



CREATE TABLE SALTO(
    ID_SALTO INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    CONSTRAINT CSE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CSD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CSH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO
);


CREATE TABLE LANCAMENTO(
    ID_LANCAMENTO INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    PESO FLOAT,
    CONSTRAINT CLE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CLD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CLH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO,
    CONSTRAINT PESO_VALIDO CHECK(PESO = 3 OR PESO = 4 OR PESO = 5 OR PESO = 6 OR PESO = 7 OR PESO = 0.500 OR PESO = 0.600 OR PESO = 0.700 OR PESO = 0.800 OR PESO = 1 OR PESO = 1.5 OR PESO = 1.75 OR PESO = 2)
);



CREATE TABLE CORRIDA(
    ID_CORRIDA INT PRIMARY KEY,
    ID_EVENTO INT,    
    ID_DECATLO INT,
    ID_HEPTATLO INT,
    CONSTRAINT CCE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO,
    CONSTRAINT CCD_FK FOREIGN KEY (ID_DECATLO) REFERENCES DECATLO,
    CONSTRAINT CCH_FK FOREIGN KEY (ID_HEPTATLO) REFERENCES HEPTATLO 
);



CREATE TABLE ESTAFETA(
    ID_ESTAFETA INT PRIMARY KEY,
    ID_EVENTO INT,    
    CONSTRAINT CEE_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO 
);



CREATE TABLE CORRIDA_ESTAFETA(
    ID_CORRIDA INT,
    ID_ESTAFETA INT,
    CONSTRAINT CCE_FK1 FOREIGN KEY (ID_CORRIDA) REFERENCES CORRIDA,   
    CONSTRAINT CCE_FK2 FOREIGN KEY (ID_ESTAFETA) REFERENCES ESTAFETA
);


CREATE TABLE PERCURSO(
    ID_ESTAFETA INT,
    ID_ATLETA INT,
    PERCURSO INT,
    CONSTRAINT CEA_FK1 FOREIGN KEY (ID_ESTAFETA) REFERENCES ESTAFETA,
    CONSTRAINT CEA_FK2 FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA,
    CONSTRAINT PERCURSO_VALIDO CHECK(PERCURSO = 1 OR PERCURSO = 2 OR PERCURSO = 3 OR PERCURSO = 4),
    CONSTRAINT CEA_UNIQUE UNIQUE (ID_ESTAFETA, ID_ATLETA, PERCURSO)
);